Fix TypeError on add-bookmark-site preferences
When opening the add-bookmark-site preferences, if there was no configuration file or if any other error occurs when loading the configuration, the preferences window never appears and the following error occurs:

Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/add-bookmark-site.py", line 103, in do_create_configure_widget
    self._urlEntry.set_text(url)
TypeError: Argument 1 does not allow None as a value

This fixes the issue by using empty strings as the default values instead of None.